#!/usr/bin/env python3
"""
Export pipeline output into the frontend's data modules.

    python export_frontend_data.py [--out out] [--frontend frontend]

The dashboard is a presentation layer over `out/`. Hand-copying numbers into JSX is how a
dashboard ends up disagreeing with the evaluation it claims to display, so the two data
modules are generated here and should never be edited by hand.

Fails loudly rather than exporting something inconsistent:
  - every case file must correspond to a trigger in held_out_triggers.json
  - no merchant may appear twice
  - the case count must equal the trigger count
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

BANNER = "// GENERATED BY export_frontend_data.py -- DO NOT EDIT BY HAND.\n"


def load_cases(casedir: Path) -> list[dict]:
    return [json.loads(p.read_text(encoding="utf-8"))
            for p in sorted(casedir.glob("DW-*.json"))]


def check(cases: list[dict], triggers: list[dict]) -> list[str]:
    """Return a list of consistency problems. Empty list means the export is safe."""
    problems: list[str] = []

    expected = {(t["merchant_id"], int(t["trigger_day"])) for t in triggers}
    found = {(c["merchant_id"], int(c["trigger_day"])) for c in cases}

    for mid, day in sorted(found - expected):
        problems.append(
            f"case file DW-{mid}-D{day:03d}.json has no matching trigger in this run "
            f"(stale output from a previous calibration)")
    for mid, day in sorted(expected - found):
        problems.append(f"trigger {mid} @ day {day} has no case file")

    seen: dict[str, int] = {}
    for c in cases:
        seen[c["merchant_id"]] = seen.get(c["merchant_id"], 0) + 1
    for mid, n in sorted(seen.items()):
        if n > 1:
            problems.append(f"{mid} appears in {n} case files; merchant ids must be unique")

    thresholds = {json.dumps(c["provenance"]["thresholds"], sort_keys=True) for c in cases}
    if len(thresholds) > 1:
        problems.append(
            f"case files cite {len(thresholds)} different threshold sets; they must all "
            f"come from one calibration")

    return problems


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="out")
    ap.add_argument("--frontend", default="frontend")
    ap.add_argument("--force", action="store_true",
                    help="export even if consistency checks fail (not recommended)")
    a = ap.parse_args()

    out, frontend = Path(a.out), Path(a.frontend)
    evfile = out / "evaluation.json"
    trigfile = out / "held_out_triggers.json"
    if not evfile.exists():
        print(f"error: {evfile} not found -- run `python run_all.py` first", file=sys.stderr)
        return 1

    evaluation = json.loads(evfile.read_text(encoding="utf-8"))
    triggers = json.loads(trigfile.read_text(encoding="utf-8"))
    cases = load_cases(out / "cases")

    problems = check(cases, triggers)
    if problems:
        print(f"{len(problems)} consistency problem(s) between out/ and the export:",
              file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        if not a.force:
            print("\nrefusing to export. re-run `python run_all.py` to rebuild out/ cleanly,"
                  "\nor pass --force to export anyway.", file=sys.stderr)
            return 1
        print("\n--force given; exporting anyway.", file=sys.stderr)

    datadir = frontend / "src" / "data"
    datadir.mkdir(parents=True, exist_ok=True)

    (datadir / "evaluationData.js").write_text(
        BANNER + "export const evaluationData = "
        + json.dumps(evaluation, indent=2) + ";\n", encoding="utf-8")
    (datadir / "casesData.js").write_text(
        BANNER + "export const casesData = "
        + json.dumps(cases, indent=2) + ";\n", encoding="utf-8")

    h = evaluation["held_out"]
    print(f"exported {len(cases)} cases and evaluation.json -> {datadir}")
    print(f"  held-out: {h['caught']}/{h['n_drifters']} caught "
          f"({h['catch_rate']:.1%}), median lead {h['median_lead_days']:.1f}d, "
          f"FP {h['false_positive_rate']:.1%}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
